spring:
  application:
    name: spring.application.name=Proj01-SCM
  datasource:
    url: jdbc:mysql://localhost:3306/scm
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080